### PR TITLE
Update rules.csv

### PR DESCRIPTION
**Pull request by pyrog**
Add french café Columbus Café & Co

See also https://github.com/osmlab/name-suggestion-index/issues/3692

### CODE REVIEW

**Comment by PanierAvide** [comment]
Checked few ones with Nominatim, they seem to be called "Columbus Café". You can either change the name in `rules.csv`, or make sure they have `brand:wikidata` tag on OSM.

**Comment by pyrog** [comment]
I checked before too 😉 

Colombus Café & Co win
And the [official website](https://www.columbuscafe.com) use both **Colombus Café & Co win** and **Colombus Café**.
See also [Q90406058](https://www.wikidata.org/wiki/Q90406058).

count | tag | name 
--|--|--
9 | name |Colombus Café & Co 
7 | name|Colombus Café
1 |name |901 colombus cafe
1|name|Colombus café
1|name|Colombus Café&Co
1|name|colombus café
1|brand|Colombus Cafe
1|brand|Colombus Café
1|brand|Colombus Café & Co
1 |operator |Colombus Café
1|internet_access:ssid|Colombus café Sousse

**Comment by PanierAvide** [comment]
As they are not so many, do you want to clean-up a bit OSM data to make the tagging coherent through France ? Or at least add `brand:wikidata` tags ?

**Comment by pyrog** [comment]
done

**Comment by PanierAvide** [comment]
Great, I will merge the pull request. I was surprised at first because the one nearest to where I live was not updated, but it's my fault (typo `Colombus` instead of `Columbus`). But I feel not so bad as I'm not the only one to do this mistake :-P http://overpass-turbo.eu/s/SNv If you have time to look up these ones as well, go for it ;-)

**Comment by pyrog** [comment]
@bmillemathias @PanierAvide Thanks Adrien for pointing this typo 😸

I will take care in a future PR for [name-suggestion-index #3692](https://github.com/osmlab/name-suggestion-index/issues/3692)

**Pull request closed without merging**
