### PR TITLE
Added Northern Ireland and Ireland legal rules.

### PR DESCRIPTION
**Pull request by HeikkiVesanto**
I am unsure why git thinks I deleted everything and re-added it.

I only added the GB - GB-NIR and IE lines and moved IT down.

### CODE REVIEW

**Comment by PanierAvide** [comment]
It might be related to new line character, you may use the Linux LF (see https://en.wikipedia.org/wiki/Newline ).

**Comment by HeikkiVesanto** [comment]
Interesting. Git CMD gives me a message when adding:

warning: LF will be replaced by CRLF in legal_rules.csv.

**Comment by PanierAvide** [comment]
Yes, you may change this Git configuration to proceed.

**Comment by HeikkiVesanto** [comment]
Ok. I will fix it later today. Sorry.

**Comment by HeikkiVesanto** [comment]
Was the date format. Excel changed it. Will create new PR.

**Pull request closed without merging**
